# Generated by Django 4.2.7 on 2023-11-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_name', models.CharField(max_length=30)),
                ('path', models.CharField(default=None, max_length=30)),
                ('is_children', models.BooleanField(default=False)),
                ('parent_id', models.IntegerField(default=None)),
            ],
        ),
    ]
