# Generated by Django 4.2.7 on 2023-11-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0002_alter_menulist_auth_name_alter_menulist_is_children_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulist',
            name='is_children',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='menulist',
            name='parent_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menulist',
            name='path',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
